import { useMemo, useState } from "react";
import {
  FaChartPie,
  FaUsers,
  FaCalendarCheck,
  FaMoneyBillWave,
  FaDownload,
  FaSearch,
  FaEye,
  FaTrash,
  FaTimes,
  FaFileAlt,
  FaTrophy,
} from "react-icons/fa";
import "./Reports.css";

const initialReports = [
  {
    id: "REP001",
    title: "Employee Summary Report",
    type: "Employee",
    department: "All Departments",
    month: "May 2026",
    generatedBy: "Admin",
    totalRecords: 82,
    status: "Completed",
    createdAt: "2026-05-30",
  },
  {
    id: "REP002",
    title: "Attendance Monthly Report",
    type: "Attendance",
    department: "IT Department",
    month: "May 2026",
    generatedBy: "Admin",
    totalRecords: 41,
    status: "Completed",
    createdAt: "2026-05-29",
  },
  {
    id: "REP003",
    title: "Salary Payment Report",
    type: "Salary",
    department: "Finance Department",
    month: "May 2026",
    generatedBy: "Admin",
    totalRecords: 22,
    status: "Pending",
    createdAt: "2026-05-28",
  },
  {
    id: "REP004",
    title: "Performance Review Report",
    type: "Performance",
    department: "IT Department",
    month: "May 2026",
    generatedBy: "HR Manager",
    totalRecords: 36,
    status: "Completed",
    createdAt: "2026-05-27",
  },
];

export default function Reports() {
  const [reports, setReports] = useState(initialReports);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("All Reports");
  const [statusFilter, setStatusFilter] = useState("All Status");
  const [viewData, setViewData] = useState(null);
  const [activeReport, setActiveReport] = useState("Employee");

  const reportTypes = [
    "All Reports",
    "Employee",
    "Attendance",
    "Salary",
    "Performance",
  ];

  const statuses = ["All Status", "Completed", "Pending"];

  const filteredReports = useMemo(() => {
    return reports.filter((item) => {
      const matchSearch =
        item.id.toLowerCase().includes(search.toLowerCase()) ||
        item.title.toLowerCase().includes(search.toLowerCase()) ||
        item.department.toLowerCase().includes(search.toLowerCase()) ||
        item.generatedBy.toLowerCase().includes(search.toLowerCase());

      const matchType =
        typeFilter === "All Reports" || item.type === typeFilter;

      const matchStatus =
        statusFilter === "All Status" || item.status === statusFilter;

      return matchSearch && matchType && matchStatus;
    });
  }, [reports, search, typeFilter, statusFilter]);

  const completedReports = reports.filter(
    (item) => item.status === "Completed"
  ).length;

  const pendingReports = reports.filter(
    (item) => item.status === "Pending"
  ).length;

  const totalRecords = reports.reduce(
    (sum, item) => sum + Number(item.totalRecords),
    0
  );

  const downloadReport = (item) => {
    const content = `
Report ID: ${item.id}
Title: ${item.title}
Type: ${item.type}
Department: ${item.department}
Month: ${item.month}
Generated By: ${item.generatedBy}
Total Records: ${item.totalRecords}
Status: ${item.status}
Created At: ${item.createdAt}
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = `${item.title}.txt`;
    a.click();
  };

  const downloadCSV = () => {
    const csv =
      "Report ID,Title,Type,Department,Month,Generated By,Total Records,Status,Created At\n" +
      reports
        .map(
          (item) =>
            `${item.id},${item.title},${item.type},${item.department},${item.month},${item.generatedBy},${item.totalRecords},${item.status},${item.createdAt}`
        )
        .join("\n");

    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = "all-reports.csv";
    a.click();
  };

  const handleDelete = (id) => {
    if (window.confirm("Are you sure you want to delete this report?")) {
      setReports((prev) => prev.filter((item) => item.id !== id));
    }
  };

  const getTypeClass = (type) => {
    if (type === "Employee") return "report-type employee";
    if (type === "Attendance") return "report-type attendance";
    if (type === "Salary") return "report-type salary";
    if (type === "Performance") return "report-type performance";
    return "report-type";
  };

  return (
    <div className="reports-page">
      <div className="reports-header">
        <div>
          <h1>Reports Management</h1>
          <span></span>
          <p>Analyze employees, attendance, salary and performance reports.</p>
        </div>

        <button onClick={downloadCSV}>
          <FaDownload /> Export Reports
        </button>
      </div>

      <div className="reports-stats">
        <div className="report-card blue">
          <FaFileAlt />
          <div>
            <h2>{reports.length}</h2>
            <p>Total Reports</p>
          </div>
        </div>

        <div className="report-card green">
          <FaChartPie />
          <div>
            <h2>{completedReports}</h2>
            <p>Completed Reports</p>
          </div>
        </div>

        <div className="report-card orange">
          <FaCalendarCheck />
          <div>
            <h2>{pendingReports}</h2>
            <p>Pending Reports</p>
          </div>
        </div>

        <div className="report-card purple">
          <FaUsers />
          <div>
            <h2>{totalRecords}</h2>
            <p>Total Records</p>
          </div>
        </div>
      </div>

      <div className="reports-summary-grid">
        <div
          className={
            activeReport === "Employee"
              ? "summary-box active-summary"
              : "summary-box"
          }
          onClick={() => setActiveReport("Employee")}
        >
          <div className="summary-icon employee">
            <FaUsers />
          </div>
          <div>
            <h3>Employee Report</h3>
            <p>Track employee count, active staff and department-wise data.</p>
          </div>
        </div>

        <div
          className={
            activeReport === "Attendance"
              ? "summary-box active-summary"
              : "summary-box"
          }
          onClick={() => setActiveReport("Attendance")}
        >
          <div className="summary-icon attendance">
            <FaCalendarCheck />
          </div>
          <div>
            <h3>Attendance Report</h3>
            <p>Monitor present, late, absent and work mode records.</p>
          </div>
        </div>

        <div
          className={
            activeReport === "Salary"
              ? "summary-box active-summary"
              : "summary-box"
          }
          onClick={() => setActiveReport("Salary")}
        >
          <div className="summary-icon salary">
            <FaMoneyBillWave />
          </div>
          <div>
            <h3>Salary Report</h3>
            <p>Review paid, pending, net salary and monthly payroll details.</p>
          </div>
        </div>

        <div
          className={
            activeReport === "Performance"
              ? "summary-box active-summary"
              : "summary-box"
          }
          onClick={() => setActiveReport("Performance")}
        >
          <div className="summary-icon performance">
            <FaTrophy />
          </div>
          <div>
            <h3>Performance Report</h3>
            <p>Analyze rating, score, tasks and employee review status.</p>
          </div>
        </div>
      </div>

      <div className="report-detail-section">
        <div className="detail-section-header">
          <div>
            <h2>{activeReport} Detailed Report</h2>
            <p>Selected report summary and department-wise analysis.</p>
          </div>

          <button onClick={downloadCSV}>
            <FaDownload /> Download
          </button>
        </div>

        {activeReport === "Employee" && (
          <>
            <div className="detail-grid">
              <div className="detail-card">
                <h3>Total Employees</h3>
                <p>82</p>
              </div>
              <div className="detail-card">
                <h3>Active Employees</h3>
                <p>76</p>
              </div>
              <div className="detail-card">
                <h3>Inactive Employees</h3>
                <p>6</p>
              </div>
              <div className="detail-card">
                <h3>Departments</h3>
                <p>4</p>
              </div>
            </div>

            <div className="mini-report-table">
              <table>
                <thead>
                  <tr>
                    <th>Department</th>
                    <th>Total Employees</th>
                    <th>Active</th>
                    <th>Inactive</th>
                    <th>Head</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>IT Department</td>
                    <td>41</td>
                    <td>39</td>
                    <td>2</td>
                    <td>Vivek Srivastava</td>
                  </tr>
                  <tr>
                    <td>HR Department</td>
                    <td>22</td>
                    <td>20</td>
                    <td>2</td>
                    <td>Neha Gupta</td>
                  </tr>
                  <tr>
                    <td>Finance Department</td>
                    <td>19</td>
                    <td>17</td>
                    <td>2</td>
                    <td>Anjali Verma</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </>
        )}

        {activeReport === "Attendance" && (
          <>
            <div className="detail-grid">
              <div className="detail-card">
                <h3>Present</h3>
                <p>68</p>
              </div>
              <div className="detail-card">
                <h3>Late</h3>
                <p>9</p>
              </div>
              <div className="detail-card">
                <h3>Absent</h3>
                <p>5</p>
              </div>
              <div className="detail-card">
                <h3>Remote</h3>
                <p>12</p>
              </div>
            </div>

            <div className="mini-report-table">
              <table>
                <thead>
                  <tr>
                    <th>Employee</th>
                    <th>Department</th>
                    <th>Present Days</th>
                    <th>Late Days</th>
                    <th>Attendance %</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Vivek Srivastava</td>
                    <td>IT Department</td>
                    <td>24</td>
                    <td>1</td>
                    <td>96%</td>
                  </tr>
                  <tr>
                    <td>Rahul Sharma</td>
                    <td>IT Department</td>
                    <td>23</td>
                    <td>2</td>
                    <td>90%</td>
                  </tr>
                  <tr>
                    <td>Priya Patel</td>
                    <td>HR Department</td>
                    <td>21</td>
                    <td>3</td>
                    <td>85%</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </>
        )}

        {activeReport === "Salary" && (
          <>
            <div className="detail-grid">
              <div className="detail-card">
                <h3>Total Paid</h3>
                <p>₹4.5L</p>
              </div>
              <div className="detail-card">
                <h3>Pending Amount</h3>
                <p>₹75K</p>
              </div>
              <div className="detail-card">
                <h3>Average Salary</h3>
                <p>₹37.5K</p>
              </div>
              <div className="detail-card">
                <h3>Pending Payments</h3>
                <p>1</p>
              </div>
            </div>

            <div className="mini-report-table">
              <table>
                <thead>
                  <tr>
                    <th>Employee</th>
                    <th>Department</th>
                    <th>Basic</th>
                    <th>Net Salary</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Vivek Srivastava</td>
                    <td>IT Department</td>
                    <td>₹40,000</td>
                    <td>₹41,423</td>
                    <td>Paid</td>
                  </tr>
                  <tr>
                    <td>Rahul Sharma</td>
                    <td>IT Department</td>
                    <td>₹35,000</td>
                    <td>₹33,712</td>
                    <td>Pending</td>
                  </tr>
                  <tr>
                    <td>Priya Patel</td>
                    <td>HR Department</td>
                    <td>₹32,000</td>
                    <td>₹31,500</td>
                    <td>Paid</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </>
        )}

        {activeReport === "Performance" && (
          <>
            <div className="detail-grid">
              <div className="detail-card">
                <h3>Excellent</h3>
                <p>18</p>
              </div>
              <div className="detail-card">
                <h3>Good</h3>
                <p>42</p>
              </div>
              <div className="detail-card">
                <h3>Average</h3>
                <p>22</p>
              </div>
              <div className="detail-card">
                <h3>Avg Score</h3>
                <p>82%</p>
              </div>
            </div>

            <div className="mini-report-table">
              <table>
                <thead>
                  <tr>
                    <th>Employee</th>
                    <th>Department</th>
                    <th>Rating</th>
                    <th>Score</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Vivek Srivastava</td>
                    <td>IT Department</td>
                    <td>5 ★</td>
                    <td>92%</td>
                    <td>Excellent</td>
                  </tr>
                  <tr>
                    <td>Rahul Sharma</td>
                    <td>IT Department</td>
                    <td>4 ★</td>
                    <td>82%</td>
                    <td>Good</td>
                  </tr>
                  <tr>
                    <td>Priya Patel</td>
                    <td>HR Department</td>
                    <td>3 ★</td>
                    <td>68%</td>
                    <td>Average</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </>
        )}
      </div>

      <div className="reports-table-card">
        <div className="reports-table-header">
          <div>
            <h2>Generated Reports</h2>
            <p>{filteredReports.length} reports found</p>
          </div>

          <div className="reports-tools">
            <div className="reports-search">
              <FaSearch />
              <input
                placeholder="Search reports..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>

            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
            >
              {reportTypes.map((type) => (
                <option key={type}>{type}</option>
              ))}
            </select>

            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
            >
              {statuses.map((status) => (
                <option key={status}>{status}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="reports-table-wrap">
          <table>
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Title</th>
                <th>Type</th>
                <th>Department</th>
                <th>Month</th>
                <th>Generated By</th>
                <th>Records</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>
              {filteredReports.length > 0 ? (
                filteredReports.map((item) => (
                  <tr key={item.id}>
                    <td>{item.id}</td>
                    <td className="report-title">{item.title}</td>
                    <td>
                      <span className={getTypeClass(item.type)}>
                        {item.type}
                      </span>
                    </td>
                    <td>{item.department}</td>
                    <td>{item.month}</td>
                    <td>{item.generatedBy}</td>
                    <td>
                      <span className="record-pill">{item.totalRecords}</span>
                    </td>
                    <td>
                      <span
                        className={
                          item.status === "Completed"
                            ? "report-status completed"
                            : "report-status pending"
                        }
                      >
                        {item.status}
                      </span>
                    </td>
                    <td>{item.createdAt}</td>
                    <td>
                      <div className="reports-actions">
                        <button
                          className="view"
                          onClick={() => setViewData(item)}
                        >
                          <FaEye />
                        </button>

                        <button
                          className="download"
                          onClick={() => downloadReport(item)}
                        >
                          <FaDownload />
                        </button>

                        <button
                          className="delete"
                          onClick={() => handleDelete(item.id)}
                        >
                          <FaTrash />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="10" className="no-report">
                    No report found
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {viewData && (
        <div className="report-modal-overlay">
          <div className="report-modal">
            <div className="report-modal-header">
              <h2>Report Details</h2>
              <button onClick={() => setViewData(null)}>
                <FaTimes />
              </button>
            </div>

            <div className="report-details">
              <p>
                <b>Report ID:</b> {viewData.id}
              </p>
              <p>
                <b>Title:</b> {viewData.title}
              </p>
              <p>
                <b>Type:</b> {viewData.type}
              </p>
              <p>
                <b>Department:</b> {viewData.department}
              </p>
              <p>
                <b>Month:</b> {viewData.month}
              </p>
              <p>
                <b>Generated By:</b> {viewData.generatedBy}
              </p>
              <p>
                <b>Total Records:</b> {viewData.totalRecords}
              </p>
              <p>
                <b>Status:</b> {viewData.status}
              </p>
              <p>
                <b>Created At:</b> {viewData.createdAt}
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}